# Generated by Django 3.2.13 on 2022-06-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_reason', models.TextField(max_length=500)),
                ('appointment_created_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_updated_date', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.IntegerField(choices=[(0, '09:00 – 09:30'), (1, '10:00 – 10:30'), (2, '11:00 – 11:30'), (3, '12:00 – 12:30'), (4, '13:00 – 13:30'), (5, '14:00 – 14:30'), (6, '15:00 – 15:30'), (7, '16:00 – 16:30'), (8, '17:00 – 17:30')])),
                ('appointment_completed', models.BooleanField(default=False)),
                ('appointment_iscancelled', models.BooleanField(default=False)),
                ('appointment_remarks', models.TextField(default=None, max_length=500)),
                ('appointment_medication', models.TextField(default=None, max_length=500)),
                ('appointment_bill', models.FloatField(default=0.0)),
                ('appointment_followup_date', models.DateField()),
            ],
        ),
    ]
