# Generated by Django 3.2.13 on 2022-06-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_newappointment_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newappointment',
            name='appointment_bill',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='newappointment',
            name='appointment_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newappointment',
            name='appointment_medication',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newappointment',
            name='appointment_remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
