# Generated by Django 3.2.13 on 2022-06-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20220627_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('C', 'Cash'), ('S', 'Stripe'), ('R', 'Razorpay')], default='', max_length=1, null=True),
        ),
    ]
