# Generated by Django 3.2.13 on 2022-06-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_payments_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newappointment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
